Don't use rosbag2_cpp/typesupport_helpers.hpp for Jazzy and later
This fixes the following compile error in Jazzy:

    src/domain_bridge/domain_bridge.cpp:38:10: fatal error:
    rosbag2_cpp/typesupport_helpers.hpp: No such file or directory
       38 | #include "rosbag2_cpp/typesupport_helpers.hpp"
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

It happens since rosbag2 release 0.26.10 and is caused by
ros2/rosbag2#2017 and its backport to Jazzy (ros2/rclcpp#2902).

We keep the previous implementation, which is needed for Humble and
add a new one, which works for Jazzy and later.

Signed-off-by: Michal Sojka <michal.sojka@cvut.cz>